### ISSUE TITLE
Adding a checklist to the newly generated card at the same time

### ISSUE THREAD

**Issue by chanelprime** [kmcroft13/submit-googleforms-to-trello#3]
Is it possible to add a checklist to the card at the same time it is generated?

**Comment by kylepinecroft** [comment]
It is technically possible but it is a more complicated enhancement because Trello only allows checklists to be added _after_ a card is already created. So the card would have to be created and then another request would need to be made to add the checklist to that new card.

Alternatively, you could copy the checklist from an existing "template" card during card creation which could be easier.
